name: Build FFI for Windows
on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'commit/tag/branch reference'
        required: true
        type: string
  workflow_call:
    inputs:
      ref:
        description: 'commit/tag/branch reference'
        required: true
        type: string

jobs:
  build:
    name: Build ${{ matrix.target }}
    runs-on: windows-latest
    strategy:
      matrix:
        target:
          - i686-pc-windows-msvc
          - x86_64-pc-windows-msvc
          - aarch64-pc-windows-msvc
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.ref }}

    - name: Rust Cache
      uses: Swatinem/rust-cache@v2.7.8
      with:
        key: ${{ matrix.target }}

    - name: Build library
      run: cargo build --release --target ${{ matrix.target }}

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: nostr-sdk-ffi-${{ matrix.target }}
        path: target/${{ matrix.target }}/release/nostr_sdk_ffi.dll
