name: Build FFI for Linux
on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'commit/tag/branch reference'
        required: true
        type: string
  workflow_call:
    inputs:
      ref:
        description: 'commit/tag/branch reference'
        required: true
        type: string

jobs:
  build:
    name: Build ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - i686-unknown-linux-gnu.2.17
          - x86_64-unknown-linux-gnu.2.17
          - armv7-unknown-linux-gnueabihf.2.17
          - aarch64-unknown-linux-gnu.2.17
          - riscv64gc-unknown-linux-gnu.2.29
          - i686-unknown-linux-musl
          - x86_64-unknown-linux-musl
          - armv7-unknown-linux-musleabihf
          - aarch64-unknown-linux-musl
          - riscv64gc-unknown-linux-musl
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.ref }}

    - name: Rust Cache
      uses: Swatinem/rust-cache@v2.7.8
      with:
        key: ${{ matrix.target }}

    - name: Install cargo-zigbuild
      run: pip install cargo-zigbuild==0.19.8

    - name: Build library
      run: cargo zigbuild --target ${{ matrix.target }} --release

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: nostr-sdk-ffi-${{ matrix.target }}
        path: target/${{ matrix.target }}/release/libnostr_sdk_ffi.so
