name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  fmt:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check
        run: bash contrib/scripts/check-fmt.sh check

  check-crate:
    name: Check crate
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Rust Cache
      uses: Swatinem/rust-cache@v2.7.8
      with:
        key: "check-crate"
    - name: Check
      run: bash contrib/scripts/check-crate.sh

  swift:
    name: Swift Package
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2.7.8
        with:
          key: "swift"

      - name: Build Swift Package
        working-directory: swift
        run: |
          bash build-xcframework.sh

      - name: Test
        working-directory: swift
        run: swift test
