name: Publish KMP
on:
  workflow_call:
    inputs:
      ref:
        description: 'commit/tag/branch reference'
        required: true
        type: string
      publish:
        description: 'value indicating whether to publish to SonaType.'
        required: true
        type: boolean
        default: false
    secrets:
      SONATYPE_TOKEN_USERNAME:
        description: 'username for gradlew publish'
        required: true
      SONATYPE_TOKEN_PASSWORD:
        description: 'password for gradlew publish'
        required: true
      MAVEN_SIGNING_SECRET_KEY:
        description: 'GPG secret key for Maven'
        required: true
      MAVEN_SIGNING_PASSWORD:
        description: 'GPG password for Maven'
        required: true

jobs:
  generate:
    name: Generate Foreign Languages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2.7.8

      - name: Install gobley-uniffi-bindgen
        run: |
          cargo install gobley-uniffi-bindgen --git https://github.com/gobley/gobley --tag v0.3.4

      - name: Build debug target
        run: |
          cargo build -p nostr-sdk-ffi --lib

      - name: Generate Kotlin Multiplatform
        run: |
          gobley-uniffi-bindgen --library target/debug/libnostr_sdk_ffi.so --config uniffi-kmp.toml -o target/uniffi/kotlin-multiplatform

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: nostr-sdk-ffi-kotlin-multiplatform
          path: target/uniffi/kotlin-multiplatform

  build-package:
    name: Build KMP & Publish
    runs-on: macos-latest
    needs: generate
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}

      - uses: actions/download-artifact@v4
        with:
          name: nostr-sdk-ffi-i686-linux-android
          path: target/i686-linux-android/release/

      - uses: actions/download-artifact@v4
        with:
          name: nostr-sdk-ffi-armv7-linux-androideabi
          path: target/armv7-linux-androideabi/release/

      - uses: actions/download-artifact@v4
        with:
          name: nostr-sdk-ffi-x86_64-linux-android
          path: target/x86_64-linux-android/release/

      - uses: actions/download-artifact@v4
        with:
          name: nostr-sdk-ffi-aarch64-linux-android
          path: target/aarch64-linux-android/release/

      - uses: actions/download-artifact@v4
        with:
          name: nostr-sdk-ffi-aarch64-apple-ios
          path: target/aarch64-apple-ios/release/

      - uses: actions/download-artifact@v4
        with:
          name: nostr-sdk-ffi-aarch64-apple-ios-sim
          path: target/aarch64-apple-ios-sim/release/

      - uses: actions/download-artifact@v4
        with:
          name: nostr-sdk-ffi-x86_64-apple-ios
          path: target/x86_64-apple-ios/release/

      - uses: actions/download-artifact@v4
        with:
          name: nostr-sdk-ffi-x86_64-apple-darwin
          path: target/x86_64-apple-darwin/release/

      - uses: actions/download-artifact@v4
        with:
          name: nostr-sdk-ffi-aarch64-apple-darwin
          path: target/aarch64-apple-darwin/release/

      - uses: actions/download-artifact@v4
        with:
          name: nostr-sdk-ffi-i686-unknown-linux-gnu
          path: target/i686-unknown-linux-gnu/release/

      - uses: actions/download-artifact@v4
        with:
          name: nostr-sdk-ffi-x86_64-unknown-linux-gnu
          path: target/x86_64-unknown-linux-gnu/release/

      - uses: actions/download-artifact@v4
        with:
          name: nostr-sdk-ffi-armv7-unknown-linux-gnueabihf
          path: target/armv7-unknown-linux-gnueabihf/release/

      - uses: actions/download-artifact@v4
        with:
          name: nostr-sdk-ffi-aarch64-unknown-linux-gnu
          path: target/aarch64-unknown-linux-gnu/release/

      - uses: actions/download-artifact@v4
        with:
          name: nostr-sdk-ffi-riscv64gc-unknown-linux-gnu
          path: target/riscv64gc-unknown-linux-gnu/release/

      - uses: actions/download-artifact@v4
        with:
          name: nostr-sdk-ffi-i686-unknown-linux-musl
          path: target/i686-unknown-linux-musl/release/

      - uses: actions/download-artifact@v4
        with:
          name: nostr-sdk-ffi-x86_64-unknown-linux-musl
          path: target/x86_64-unknown-linux-musl/release/

      - uses: actions/download-artifact@v4
        with:
          name: nostr-sdk-ffi-armv7-unknown-linux-musleabihf
          path: target/armv7-unknown-linux-musleabihf/release/

      - uses: actions/download-artifact@v4
        with:
          name: nostr-sdk-ffi-aarch64-unknown-linux-musl
          path: target/aarch64-unknown-linux-musl/release/

      - uses: actions/download-artifact@v4
        with:
          name: nostr-sdk-ffi-riscv64gc-unknown-linux-musl
          path: target/riscv64gc-unknown-linux-musl/release/

      - uses: actions/download-artifact@v4
        with:
          name: nostr-sdk-ffi-x86_64-unknown-freebsd
          path: target/x86_64-unknown-freebsd/release/

      - uses: actions/download-artifact@v4
        with:
          name: nostr-sdk-ffi-i686-pc-windows-msvc
          path: target/i686-pc-windows-msvc/release/

      - uses: actions/download-artifact@v4
        with:
          name: nostr-sdk-ffi-x86_64-pc-windows-msvc
          path: target/x86_64-pc-windows-msvc/release/

      - uses: actions/download-artifact@v4
        with:
          name: nostr-sdk-ffi-aarch64-pc-windows-msvc
          path: target/aarch64-pc-windows-msvc/release/

      - uses: actions/download-artifact@v4
        with:
          name: nostr-sdk-ffi-kotlin-multiplatform
          path: target/uniffi/kotlin-multiplatform

      - name: Assemble KMP
        working-directory: kmp
        run: bash assemble.sh

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: nostr-sdk-ffi-kmp-aar
          path: kmp/nostr-sdk-kmp/build/outputs/aar/nostr-sdk-kmp-release.aar

      - name: Publish
        if: ${{ inputs.publish }}
        working-directory: kmp
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.SONATYPE_TOKEN_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.SONATYPE_TOKEN_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.MAVEN_SIGNING_SECRET_KEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.MAVEN_SIGNING_PASSWORD }}
        run: |
          ./gradlew publishToMavenCentral --no-configuration-cache
